receivers:
  otlp:
    protocols:
      grpc: { endpoint: 0.0.0.0:4317 }   # optional
      http: { endpoint: 0.0.0.0:4318 }   # <-- required for 4318


processors:
  batch:

exporters:
  otlphttp/jaeger:
    endpoint: http://jaeger:4318
#  otlp/jaeger:
#    endpoint: 172.47.0.2:4317 # https
#    tls:
#      insecure: true           # Jaeger all-in-one uses plain HTTP for 4317 in many builds
  debug:
    verbosity: detailed   # or "basic"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/jaeger,debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
